// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package alertsls

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostslsAlertsReader is a Reader for the PostslsAlerts structure.
type PostslsAlertsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostslsAlertsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostslsAlertsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostslsAlertsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostslsAlertsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostslsAlertsOK creates a PostslsAlertsOK with default headers values
func NewPostslsAlertsOK() *PostslsAlertsOK {
	return &PostslsAlertsOK{}
}

/*PostslsAlertsOK handles this case with default header values.

Create alerts response
*/
type PostslsAlertsOK struct {
}

func (o *PostslsAlertsOK) Error() string {
	return fmt.Sprintf("[POST /alerts/sls][%d] postslsAlertsOK ", 200)
}

func (o *PostslsAlertsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostslsAlertsBadRequest creates a PostslsAlertsBadRequest with default headers values
func NewPostslsAlertsBadRequest() *PostslsAlertsBadRequest {
	return &PostslsAlertsBadRequest{}
}

/*PostslsAlertsBadRequest handles this case with default header values.

Bad request
*/
type PostslsAlertsBadRequest struct {
	Payload string
}

func (o *PostslsAlertsBadRequest) Error() string {
	return fmt.Sprintf("[POST /alerts/sls][%d] postslsAlertsBadRequest  %+v", 400, o.Payload)
}

func (o *PostslsAlertsBadRequest) GetPayload() string {
	return o.Payload
}

func (o *PostslsAlertsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostslsAlertsInternalServerError creates a PostslsAlertsInternalServerError with default headers values
func NewPostslsAlertsInternalServerError() *PostslsAlertsInternalServerError {
	return &PostslsAlertsInternalServerError{}
}

/*PostslsAlertsInternalServerError handles this case with default header values.

Internal server error
*/
type PostslsAlertsInternalServerError struct {
	Payload string
}

func (o *PostslsAlertsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /alerts/sls][%d] postslsAlertsInternalServerError  %+v", 500, o.Payload)
}

func (o *PostslsAlertsInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *PostslsAlertsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
